trigger:
  paths:
    include:
      - project/*
      - scripts/*
      - k8s-manifests/*

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '7c00a488-362e-4498-a13a-ed0a92de7325'
  imageRepository: 'covidbedslotbooking'
  containerRegistry: 'covidcicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/project/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'covidagent'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    env:
      DOCKER_BUILDKIT: '1'  # ✅ Enable BuildKit
    steps:
    - script: echo "Starting Docker build with BuildKit..."
      displayName: 'Pre-Build Message'

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'

- stage: Push
  displayName: Push stage
  dependsOn: Build
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

- stage: Update
  displayName: Update k8s manifests
  dependsOn: Push
  jobs:
  - job: Update
    displayName: Update manifest
    steps:
    - script: chmod +x scripts/updatek8sManifests.sh
      displayName: Make update script executable

    - task: ShellScript@2
      displayName: Update K8s Image in Manifest
      inputs:
        scriptPath: 'scripts/updatek8sManifests.sh'
        args: 'backend $(containerRegistry)/$(imageRepository):$(tag)'
